Repository antvis/GPT-Vis, pull requests merged in 2024-12, with the labels that each got.

#41 fix: ssr render err for map
  .changeset/odd-ways-draw.md
  .changeset/pre.json
  .dumirc.ts
  .fatherrc.ts
  .github/workflows/preview.yml
  .gitignore
  CHANGELOG.md
  mako.config.json
  package.json
  src/export-map.browser.ts
  src/export-map.ts
  src/export.ts
  src/version.ts
  tsconfig.eslint.json
  tsconfig.json
Labels: pr(bugfix)

#45 docs: add video demo
  README.ja-JP.md
  README.md
  README.zh-CN.md
Labels: pr(documentation)

#48 feat(comp): optimize flow diagram layout
  src/ConfigProvider/hooks/useConfig.ts
  src/FlowDiagram/helper.ts
  src/FlowDiagram/index.tsx
Labels: pr(feature)

#49 fix: theme undefined with antd@4
  .changeset/silent-buckets-grab.md
  src/Text/utils/useAntdDarkAlgorithm.ts
Labels: pr(bugfix)

#51 feat: map support update
  .changeset/strange-turtles-allow.md
  src/Map/Component/MapView.tsx
  src/Map/Component/Marker.tsx
  src/Map/Component/Polyline.tsx
  src/Map/Component/index.tsx
  src/Map/index.tsx
  src/utils/map/context.ts
  src/utils/map/view.ts
Labels: pr(feature)

#53 fix: config plot axis
  .changeset/shy-singers-reply.md
  src/ConfigProvider/hooks/useConfig.ts
  src/utils/plot.ts
Labels: pr(bugfix)

#60 docs: add custom ui demo
  .dumirc.ts
  docs/guide/custom-ui.md
  docs/guide/customize-style.md
  docs/guide/demos/WeatherCard/index.tsx
  docs/guide/demos/WeatherCard/style.ts
  docs/guide/demos/custom-ui.tsx
  mako.config.json
  src/Area/index.md
  src/Bar/index.md
  src/ChartCodeRender/index.md
  src/Column/index.md
  src/ConfigProvider/hooks/useConfig.ts
  src/ConfigProvider/index.md
  src/DualAxes/index.md
  src/FishboneDiagram/index.md
  src/FlowDiagram/index.md
  src/GPTVis/index.md
  src/HeatMap/index.md
  src/Histogram/index.md
  src/IndentedTree/index.md
  src/Line/index.md
  src/Map/index.md
  src/MindMap/index.md
  src/NetworkGraph/index.md
  src/OrganizationChart/index.md
  src/PathMap/index.md
  src/Pie/index.md
  src/PinMap/index.md
  src/Radar/index.md
  src/Scatter/index.md
  src/Text/index.md
  src/Treemap/index.md
  src/WordCloud/index.md
  tsconfig.json
Labels: pr(documentation)

#62 feat: add event for data communicate
  .changeset/slow-drinks-thank.md
  package.json
  src/GPTVis/Lite.tsx
  src/GPTVis/demos/context-provider.tsx
  src/GPTVis/demos/event.tsx
  src/GPTVis/hooks/useContext.ts
  src/GPTVis/hooks/useEvent.ts
  src/GPTVis/index.md
  src/index.ts
Labels: pr(feature)

#64 fix: add style props for map
  .changeset/eighty-dingos-sing.md
  src/Map/index.tsx
  src/types/chart.ts
Labels: pr(bugfix)

#66 feat(text): optimize vis-text margin
  .changeset/yellow-pumas-deny.md
  src/Text/VisText.tsx
Labels: pr(feature)
