Repository antvis/GPT-Vis, pull requests merged in 2024-11, with the labels that each got.

#6 docs: document link
  README.md
  README.zh-CN.md
Labels: pr(documentation)

#7 feat: streamlit with gpt-vis
  README.md
  README.zh-CN.md
  bindings/streamlit-gpt-vis/.flake8
  bindings/streamlit-gpt-vis/.gitignore
  bindings/streamlit-gpt-vis/LICENSE
  bindings/streamlit-gpt-vis/MANIFEST.in
  bindings/streamlit-gpt-vis/README.md
  bindings/streamlit-gpt-vis/example/basic.py
  bindings/streamlit-gpt-vis/setup.py
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/__init__.py
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/.gitignore
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/README.md
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/eslint.config.js
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/index.html
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/package.json
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/public/bootstrap.min.css
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/src/MyComponent.tsx
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/src/index.css
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/src/main.tsx
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/src/vite-env.d.ts
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/tsconfig.app.json
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/tsconfig.json
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/tsconfig.node.json
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/vite.config.ts
  eslint.config.js
Labels: pr(feature)

#10 feat: graph supports global configuration
  .changeset/wise-geese-camp.md
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/public/bootstrap.min.css
  src/ConfigProvider/hooks/useConfig.ts
  src/ConfigProvider/index.md
  src/types/config.ts
Labels: pr(feature)

#11 docs(text): delete playground demo for veriry
  src/Text/demos/playground-dataset-check.tsx
  src/Text/index.md
Labels: pr(documentation)

#12 feat: lite component for GPTVis
  .changeset/witty-camels-stare.md
  README.md
  README.zh-CN.md
  docs/guide/quick-start.md
  eslint.config.js
  src/Area/demos/markdown.tsx
  src/Area/demos/stack.tsx
  src/Bar/demos/group.tsx
  src/Bar/demos/markdown.tsx
  src/Bar/demos/stack.tsx
  src/ChartCodeRender/demos/common.tsx
  src/ChartCodeRender/demos/default.tsx
  src/ChartCodeRender/demos/extra.tsx
  src/ChartCodeRender/demos/stream.tsx
  src/Column/demos/group.tsx
  src/Column/demos/markdown.tsx
  src/Column/demos/stack.tsx
  src/DualAxes/demos/markdown.tsx
  src/DualAxes/demos/multiple.tsx
  src/FlowDiagram/demos/markdown.tsx
  src/GPTVis/Lite.tsx
  src/GPTVis/demos/code.tsx
  src/GPTVis/demos/default.tsx
  src/GPTVis/demos/tag.tsx
  src/GPTVis/index.md
  src/GPTVis/index.tsx
  src/HeatMap/index.md
  src/Histogram/demos/markdown.tsx
  src/IndentedTree/demos/markdown.tsx
  src/Line/demos/category.tsx
  src/Line/demos/markdown.tsx
  src/MindMap/demos/markdown.tsx
  src/NetworkGraph/demos/markdown.tsx
  src/OrganizationChart/demos/markdown.tsx
  src/PathMap/demos/markdown.tsx
  src/Pie/demos/markdown.tsx
  src/PinMap/demos/markdown.tsx
  src/Radar/demos/category.tsx
  src/Radar/demos/markdown.tsx
  src/Scatter/demos/markdown.tsx
  src/Treemap/demos/markdown.tsx
  src/WordCloud/index.md
  src/export.ts
  src/index.ts
Labels: pr(feature)

#9 docs: line chart eval
  eslint.config.js
  evaluations/.gitignore
  evaluations/README.md
  evaluations/config.json
  evaluations/datastes/chart/line/eval.json
  evaluations/datastes/chart/line/metrics.json
  evaluations/datastes/chart/line/test.json
  evaluations/datastes/intention/.gitkeep
  evaluations/package.json
  evaluations/prompts/agent.md
  evaluations/prompts/line/data2chart.md
  evaluations/prompts/line/text2chart.md
  evaluations/scripts/constants/index.js
  evaluations/scripts/eval/eval-data.js
  evaluations/scripts/eval/eval-metrics.js
  evaluations/scripts/helpers/agent-request.js
  evaluations/scripts/helpers/chart-schema.js
  evaluations/scripts/helpers/evaluate-text.js
  evaluations/scripts/helpers/evaluate.js
  evaluations/scripts/helpers/markdown2txt.js
  evaluations/scripts/helpers/read-dataset.js
  evaluations/scripts/helpers/read-knowledge.js
  evaluations/scripts/prompt/column-data2chart.js
  evaluations/scripts/prompt/column-text2chart.js
  evaluations/scripts/prompt/data2chart.js
  evaluations/scripts/prompt/generate-prompts.js
  evaluations/scripts/prompt/line-data2chart.js
  evaluations/scripts/prompt/line-text2chart.js
  evaluations/scripts/prompt/pie-data2chart.js
  evaluations/scripts/prompt/pie-text2chart.js
  evaluations/scripts/prompt/text2chart.js
  knowledges/折线图 - Line Chart.md
  knowledges/知识库总览.md
  prompts/chart-type.md
  prompts/chart-vis.md
  prompts/intent-recognition.md
  prompts/question-classification.md
  prompts/vis-consult.md
Labels: pr(documentation)

#13 fix(text): vis-text use parent container font-size
  .changeset/rich-horses-look.md
  src/Text/VisText.tsx
  src/Text/demos/markdown.tsx
Labels: pr(bugfix)

#14 docs: eval column
  evaluations/datastes/chart/column/eval.json
  evaluations/datastes/chart/column/metrics.json
  evaluations/datastes/chart/column/test.json
  evaluations/package.json
  evaluations/prompts/column/data2chart.md
  evaluations/prompts/column/text2chart.md
  evaluations/scripts/helpers/agent-request.js
  knowledges/柱形图 - Column Chart.md
Labels: pr(documentation)

#16 docs: eval dual-axes
  evaluations/datastes/chart/dual-axes/eval.json
  evaluations/datastes/chart/dual-axes/metrics.json
  evaluations/datastes/chart/dual-axes/test.json
  evaluations/prompts/dual-axes-chart/data2chart.md
  evaluations/prompts/dual-axes-chart/text2chart.md
  knowledges/双轴图 - DualAxes Chart.md
Labels: pr(documentation)

#18 feat: fishbone diagram component
  .changeset/slow-spiders-raise.md
  evaluations/datastes/chart/dual-axes/eval.json
  evaluations/datastes/chart/dual-axes/metrics.json
  evaluations/datastes/chart/dual-axes/test.json
  evaluations/prompts/dual-axes-chart/data2chart.md
  evaluations/prompts/dual-axes-chart/text2chart.md
  package.json
  src/FishboneDiagram/demos/common.tsx
  src/FishboneDiagram/demos/markdown.tsx
  src/FishboneDiagram/index.md
  src/FishboneDiagram/index.tsx
  src/export.ts
  src/types/chart.ts
Labels: pr(feature)

#19 docs: eval fishbone flowdiagram mindmap networkgraph orgchart
  evaluations/datastes/chart/fishbone-diagram/eval.json
  evaluations/datastes/chart/fishbone-diagram/metrics.json
  evaluations/datastes/chart/fishbone-diagram/test.json
  evaluations/datastes/chart/flow-diagram/eval.json
  evaluations/datastes/chart/flow-diagram/metrics.json
  evaluations/datastes/chart/flow-diagram/test.json
  evaluations/datastes/chart/mind-map/eval.json
  evaluations/datastes/chart/mind-map/metrics.json
  evaluations/datastes/chart/mind-map/test.json
  evaluations/datastes/chart/network-graph/eval.json
  evaluations/datastes/chart/network-graph/metrics.json
  evaluations/datastes/chart/network-graph/test.json
  evaluations/datastes/chart/organization-chart/eval.json
  evaluations/datastes/chart/organization-chart/metrics.json
  evaluations/datastes/chart/organization-chart/test.json
  evaluations/prompts/fishbone-diagram/data2chart.md
  evaluations/prompts/fishbone-diagram/text2chart.md
  evaluations/prompts/flow-diagram/data2chart.md
  evaluations/prompts/flow-diagram/text2chart.md
  evaluations/prompts/mind-map/data2chart.md
  evaluations/prompts/mind-map/text2chart.md
  evaluations/prompts/network-graph/data2chart.md
  evaluations/prompts/network-graph/text2chart.md
  evaluations/prompts/organization-chart/data2chart.md
  evaluations/prompts/organization-chart/text2chart.md
  knowledges/思维导图 - Mind Map.md
  knowledges/流程图 - Flow Diagram.md
  knowledges/组织架构图 - Organization Chart.md
  knowledges/网络图 - Network Graph.md
  knowledges/鱼骨图 - Fishbone Diagram.md
Labels: pr(documentation)

#22 docs: eval scatter radar treemap histogram, knowledge treemap
  evaluations/datastes/chart/histogram/eval.json
  evaluations/datastes/chart/histogram/metrics.json
  evaluations/datastes/chart/histogram/test.json
  evaluations/datastes/chart/radar/eval.json
  evaluations/datastes/chart/radar/metrics.json
  evaluations/datastes/chart/radar/test.json
  evaluations/datastes/chart/scatter/eval.json
  evaluations/datastes/chart/scatter/metrics.json
  evaluations/datastes/chart/scatter/test.json
  evaluations/datastes/chart/treemap/eval.json
  evaluations/datastes/chart/treemap/metrics.json
  evaluations/datastes/chart/treemap/test.json
  evaluations/prompts/histogram-chart/data2chart.md
  evaluations/prompts/histogram-chart/text2chart.md
  evaluations/prompts/radar/data2chart.md
  evaluations/prompts/radar/text2chart.md
  evaluations/prompts/scatter/data2chart.md
  evaluations/prompts/scatter/text2chart.md
  evaluations/prompts/treemap-chart/data2chart.md
  evaluations/prompts/treemap-chart/text2chart.md
  knowledges/矩阵树图 -Treemap Chart.md
Labels: pr(documentation)

#23 docs: add text knowledge
  knowledges/数据文本 - Vis Text.md
Labels: pr(documentation)

#25 docs: add evaluation dataset for narrative text
  evaluations/datastes/chart/text/eval.json
  evaluations/datastes/chart/text/metrics.json
  evaluations/datastes/chart/text/test.json
  evaluations/prompts/narrative-text/agent.md
  evaluations/prompts/narrative-text/text2chart.md
Labels: pr(documentation)

#27 docs: visual knowledge
  .github/workflows/ci.yml
  .prettierignore
  README.md
  README.zh-CN.md
  evaluations/.prettierignore
  evaluations/datastes/chart/text/eval.json
  evaluations/datastes/chart/text/metrics.json
  evaluations/prompts/narrative-text/agent.md
  evaluations/prompts/narrative-text/text2chart.md
  prompts/chart-vis.md
  prompts/intent-recognition.md
  prompts/vis-consult.md
Labels: pr(documentation)

#20 docs: dataset for chart recommendation evaluation and fine-tuning
  .github/workflows/ci.yml
  .prettierignore
  README.md
  README.zh-CN.md
  evaluations/datastes/recommend/README.en.md
  evaluations/datastes/recommend/README.md
  evaluations/datastes/recommend/column/01_base.json
  evaluations/datastes/recommend/column/02_split.json
  evaluations/datastes/recommend/eval.json
  evaluations/datastes/recommend/flow-diagram/01_base.json
  evaluations/datastes/recommend/funnel/01_base.json
  evaluations/datastes/recommend/gpt_vis_train.jsonl
  evaluations/datastes/recommend/heatmap/01_two_dim_one_measure.json
  evaluations/datastes/recommend/histogram/01_values.json
  evaluations/datastes/recommend/line/01_base.json
  evaluations/datastes/recommend/line/02_multi_measure.json
  evaluations/datastes/recommend/line/03_split.json
  evaluations/datastes/recommend/map/01_long_lat.json
  evaluations/datastes/recommend/metrics.json
  evaluations/datastes/recommend/mind-map/01_base.json
  evaluations/datastes/recommend/multiple-axes/01_base.json
  evaluations/datastes/recommend/network-graph/01_base.json
  evaluations/datastes/recommend/pie/01_base.json
  evaluations/datastes/recommend/progress/01_base.json
  evaluations/datastes/recommend/radar/01_single_item.json
  evaluations/datastes/recommend/radar/02_measure_dimension.json
  evaluations/datastes/recommend/radar/03_split.json
  evaluations/datastes/recommend/scatter/01_two_measure_correlate.json
  evaluations/datastes/recommend/scatter/02_split.json
  evaluations/datastes/recommend/scatter/03_split_and_size.json
  evaluations/datastes/recommend/treemap/01_base.json
  evaluations/datastes/recommend/word-cloud/01_base.json
  evaluations/package.json
  evaluations/scripts/eval/eval-recommend.js
  evaluations/scripts/helpers/evaluate-chart-encode.js
  evaluations/scripts/helpers/read-dataset.js
  prompts/chart-recommend.md
Labels: pr(documentation)

#32 docs: Update antd-design-x.md
  docs/guide/antd-design-x.md
Labels: pr(documentation)

#33 docs: fix typo in .dumirc.ts
  .dumirc.ts
Labels: pr(documentation)

#37 feat: support table paraser
  .changeset/tall-roses-change.md
  bindings/streamlit-gpt-vis/streamlit_gpt_vis/frontend/public/bootstrap.min.css
  package.json
  src/GPTVis/Lite.tsx
Labels: pr(feature)

#39 docs: add Japanese README
  README.ja-JP.md
  README.md
  README.zh-CN.md
Labels: pr(documentation)
