Repository antvis/GPT-Vis, pull requests merged in 2025-04, with the labels that each got.

#80 feat: 流程图节点使用默认颜色，文档替换示例数据
  .changeset/tricky-apples-tell.md
  src/FlowDiagram/demos/common.tsx
  src/FlowDiagram/index.tsx
Labels: pr(feature)

#82 chore: update live demo in README.md file
  README.md
Labels: ignore-for-release

#84 fix: rerender for pinmap
  .changeset/thick-garlics-enter.md
  src/HeatMap/index.tsx
  src/PathMap/index.tsx
  src/PinMap/index.tsx
  src/utils/map/style.ts
Labels: pr(bugfix)

#86 fix: map bound
  .changeset/purple-wolves-enjoy.md
  src/utils/map/view.ts
Labels: pr(bugfix)

#83 feat: add gpt-vis SSR
  .changeset/pre.json
  .changeset/salty-berries-like.md
  .gitignore
  __tests__/index.test.ts
  package.json
  src/ssr/area.ts
  src/ssr/bar.ts
  src/ssr/column.ts
  src/ssr/dual-axes.ts
  src/ssr/fishbone-diagram.ts
  src/ssr/flow-diagram.ts
  src/ssr/histogram.ts
  src/ssr/index.ts
  src/ssr/line.ts
  src/ssr/mind-map.ts
  src/ssr/network-graph.ts
  src/ssr/pie.ts
  src/ssr/radar.ts
  src/ssr/scatter.ts
  src/ssr/treemap.ts
  src/ssr/type.ts
  src/ssr/word-cloud.ts
Labels: pr(feature)
