Repository antvis/GPT-Vis, pull requests merged in 2025-07, with the labels that each got.

#135 feat: bar label fixed
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-group-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-stacked.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-grouped-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked-label.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column.png
  bindings/gpt-vis-ssr/src/vis/bar.ts
  bindings/gpt-vis-ssr/src/vis/column.ts
Labels: pr(feature)

#136 feat: feat insetRight add nice
  bindings/gpt-vis-ssr/__tests__/area.spec.ts
  bindings/gpt-vis-ssr/__tests__/snapshot/area-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-grouped-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-group-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar-stacked.png
  bindings/gpt-vis-ssr/__tests__/snapshot/bar.png
  bindings/gpt-vis-ssr/__tests__/snapshot/boxplot-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/boxplot-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/boxplot-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/boxplot.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-grouped-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked-label.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column-stacked.png
  bindings/gpt-vis-ssr/__tests__/snapshot/column.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-order.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes.png
  bindings/gpt-vis-ssr/__tests__/snapshot/histogram-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/histogram-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/histogram.png
  bindings/gpt-vis-ssr/__tests__/snapshot/line-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/line-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/line-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/line.png
  bindings/gpt-vis-ssr/__tests__/snapshot/liquid academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/liquid.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph.png
  bindings/gpt-vis-ssr/__tests__/snapshot/scatter-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/scatter-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/scatter.png
  bindings/gpt-vis-ssr/__tests__/snapshot/violin-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/violin-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/violin-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/violin.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud.png
  bindings/gpt-vis-ssr/package.json
  bindings/gpt-vis-ssr/src/vis/area.ts
  bindings/gpt-vis-ssr/src/vis/bar.ts
  bindings/gpt-vis-ssr/src/vis/boxplot.ts
  bindings/gpt-vis-ssr/src/vis/column.ts
  bindings/gpt-vis-ssr/src/vis/dual-axes.ts
  bindings/gpt-vis-ssr/src/vis/histogram.ts
  bindings/gpt-vis-ssr/src/vis/line.ts
  bindings/gpt-vis-ssr/src/vis/scatter.ts
  bindings/gpt-vis-ssr/src/vis/violin.ts
Labels: pr(feature)

#137 feat: update version
  bindings/gpt-vis-ssr/package.json
Labels: pr(feature)

#142 feat: add errorRender
  package.json
  src/ChartCodeRender/ErrorComponent.tsx
  src/ChartCodeRender/VisChart.tsx
  src/ChartCodeRender/demos/errorRender.tsx
  src/ChartCodeRender/index.md
  src/ChartCodeRender/index.tsx
  src/ChartCodeRender/type.ts
  src/index.ts
Labels: pr(feature)

#143 feat: area add point
  bindings/gpt-vis-ssr/__tests__/snapshot/area-grouped-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-grouped.png
  bindings/gpt-vis-ssr/__tests__/snapshot/area-stacked-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/fishbone-diagram-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/fishbone-diagram-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/fishbone-diagram.png
  bindings/gpt-vis-ssr/__tests__/snapshot/flow-diagram-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/flow-diagram-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/flow-diagram-text-ellipsis.png
  bindings/gpt-vis-ssr/__tests__/snapshot/flow-diagram.png
  bindings/gpt-vis-ssr/__tests__/snapshot/liquid academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/liquid-rough.png
  bindings/gpt-vis-ssr/__tests__/snapshot/liquid.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph-rough.png
  bindings/gpt-vis-ssr/__tests__/snapshot/network-graph.png
  bindings/gpt-vis-ssr/__tests__/snapshot/organization-chart-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/organization-chart-horizontal.png
  bindings/gpt-vis-ssr/__tests__/snapshot/organization-chart.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud-rough.png
  bindings/gpt-vis-ssr/__tests__/snapshot/word-cloud.png
  bindings/gpt-vis-ssr/src/vis/area.ts
Labels: pr(feature)

#146 feat: version update to publish rough
  bindings/gpt-vis-ssr/package.json
Labels: pr(feature)

#153 feat: catch error and add error render ui
  .changeset/light-areas-attack.md
  docs/guide/antd-design-x.md
  docs/guide/customize-style.md
  docs/guide/demos/custom-ui.tsx
  package.json
  src/Area/demos/markdown.tsx
  src/Area/demos/stack.tsx
  src/Bar/demos/group.tsx
  src/Bar/demos/markdown.tsx
  src/Bar/demos/stack.tsx
  src/ChartCodeRender/VisChart.tsx
  src/ChartCodeRender/demos/errorRender.tsx
  src/ChartCodeRender/demos/stream.tsx
  src/ChartCodeRender/index.md
  src/ChartCodeRender/index.tsx
  src/ChartCodeRender/styles.ts
  src/ChartCodeRender/type.ts
  src/ChartCodeRender/utils.ts
  src/Column/demos/group.tsx
  src/Column/demos/markdown.tsx
  src/Column/demos/stack.tsx
  src/DualAxes/demos/markdown.tsx
  src/DualAxes/demos/multiple.tsx
  src/FishboneDiagram/demos/markdown.tsx
  src/FlowDiagram/demos/markdown.tsx
  src/GPTVis/demos/errorRender.tsx
  src/GPTVis/demos/relation.tsx
  src/GPTVis/index.md
  src/HeatMap/index.md
  src/Histogram/demos/markdown.tsx
  src/IndentedTree/demos/markdown.tsx
  src/Line/demos/category.tsx
  src/Line/demos/markdown.tsx
  src/MindMap/demos/markdown.tsx
  src/NetworkGraph/demos/markdown.tsx
  src/OrganizationChart/demos/markdown.tsx
  src/PathMap/demos/markdown.tsx
  src/Pie/demos/markdown.tsx
  src/PinMap/demos/markdown.tsx
  src/Radar/demos/category.tsx
  src/Radar/demos/markdown.tsx
  src/Scatter/demos/markdown.tsx
  src/Text/demos/custom-markdown.tsx
  src/Text/demos/markdown.tsx
  src/Treemap/demos/markdown.tsx
  src/WordCloud/index.md
  src/index.ts
Labels: pr(feature)

#161 feat: add copy feedback
  .changeset/brave-buttons-wait.md
  src/ChartCodeRender/VisChart.tsx
Labels: pr(feature)

#160 fix: error render style
  src/ChartCodeRender/demos/errorRender.tsx
  src/ChartCodeRender/index.md
  src/ChartCodeRender/styles.ts
Labels: pr(bugfix)

#165 fix: css error
  .changeset/three-deer-open.md
  src/ChartCodeRender/styles.ts
Labels: pr(bugfix)

#172 fix: dual-axes axisXTitle bug
  bindings/gpt-vis-ssr/__tests__/dual-axes.spec.ts
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-academy.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-custom-style.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-order.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-required.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes-rough.png
  bindings/gpt-vis-ssr/__tests__/snapshot/dual-axes.png
  bindings/gpt-vis-ssr/src/vis/dual-axes.ts
Labels: pr(bugfix)

#174 fix: fix line point color style
  bindings/gpt-vis-ssr/__tests__/line.spec.ts
  bindings/gpt-vis-ssr/__tests__/snapshot/line-grouped.png
  bindings/gpt-vis-ssr/src/vis/line.ts
Labels: pr(bugfix)

#177 feat: add download image btn
  .changeset/eleven-trams-behave.md
  package.json
  src/ChartCodeRender/VisChart.tsx
  src/ChartCodeRender/icon.tsx
Labels: pr(feature)

#179 chore: version
  bindings/gpt-vis-ssr/package.json
Labels: ignore-for-release
